### ISSUE TITLE
Problem with the cyanaudit migration

### ISSUE THREAD

**Issue by gaboesquivel** [EOSIO/demux-js-postgres#67]
@flux627 I'm still having issues with the latest version.  

It seems there might be a problem with the cyanaudit migration. 

<img width="1369" alt="demux-postgres" src="https://user-images.githubusercontent.com/391270/56211679-9ca2b780-6015-11e9-8daa-f5c240b98a5d.png">

First tried 4.0.1, now I'm using master with npm link with console.log to debug

rel #65

**Comment by conr2d** [comment]
This issue is caused by using different version of `pg-promise`. `QueryFile` class from different version of `pg-promise` are incompatible. (vitaly-t/pg-promise#393)

`demux-postgres` depends on `massive@5.7.2` and `pg-promise@8.5.3`, but `demux-eos` depends on `massive@^5.7.5`, so installed `massive` on root of node_modules and `massive` on which `demux-postgres` depends will be different:
```
├┬massive@5.7.7
│└─pg-promise@8.5.6
├┬demux-postgres@4.0.1
│└┬massive@5.7.2
│ └─pg-promise@8.5.3
```
I think it would be better to make the dependent version of `massive` identical on both `demux-eos` and `demux-postgres` packages.

**Comment by flux627** [comment]
Issue resolved by #69

**Comment by jasonbert** [comment]
@flux627 closing my own issue as it's a duplicate of this one. I've changed the demux packages to all use edge, which I believe contains your #69 fix.

![image](https://user-images.githubusercontent.com/2347572/63656056-7c36f680-c787-11e9-942c-9bc43da446ee.png)

However, `massive` is coming back as `undefined` when I attempt to import it.

![image](https://user-images.githubusercontent.com/2347572/63656049-6e817100-c787-11e9-990d-164ff25b3823.png)

I can definitely see the export in the dist

![image](https://user-images.githubusercontent.com/2347572/63656081-b7392a00-c787-11e9-8092-6f09e3031bd7.png)

**Comment by jasonbert** [comment]
Just to add a bit more, if I install `massive@5.11.0`, which is the version `demux-postgre` from the develop branch is using, I still get the cyanaudit problem mentioned by @gaboesquivel when using `const massive = require("massive")`

**Comment by jasonbert** [comment]
I had to remove `default` because there is not default property on `massive_1`

![image](https://user-images.githubusercontent.com/2347572/63793792-554c0200-c8f8-11e9-987a-528ab4269340.png)
